export const ICON_LIST = [
  { title: 'Shield Check', value: 'shield-check' },
  { title: 'Shield Alert', value: 'shield-alert' },
  { title: 'Shield', value: 'shield' },
  { title: 'Home', value: 'home' },
  { title: 'Scale', value: 'scale' },
  { title: 'Message Circle', value: 'message-circle' },
  { title: 'Search', value: 'search' },
  { title: 'Grid', value: 'grid' },
  { title: 'Zap', value: 'zap' },
  { title: 'Check Circle', value: 'check-circle' },
  { title: 'Star', value: 'star' },
  { title: 'Award', value: 'award' },
  { title: 'Arrow Right', value: 'arrow-right' },
  { title: 'Chevron Right', value: 'chevron-right' },
  { title: 'Chevron Up', value: 'chevron-up' },
  { title: 'User Check', value: 'user-check' },
  { title: 'Users', value: 'users' },
  { title: 'File Text', value: 'file-text' },
  { title: 'Scroll Text', value: 'scroll-text' },
  { title: 'Move Right', value: 'move-right' },
  { title: 'Landmark', value: 'landmark' },
  { title: 'Hand Heart', value: 'hand-heart' },
  { title: 'Briefcase', value: 'briefcase' },
  { title: 'Gavel', value: 'gavel' },
  { title: 'Building', value: 'building' },
  { title: 'Building 2', value: 'building-2' },
  { title: 'Key', value: 'key' },
  { title: 'Door Open', value: 'door-open' },
  { title: 'Map Pin', value: 'map-pin' },
  { title: 'Phone', value: 'phone' },
  { title: 'Mail', value: 'mail' },
  { title: 'Send', value: 'send' },
  { title: 'Clock', value: 'clock' },
  { title: 'Calendar', value: 'calendar' },
  { title: 'Lock', value: 'lock' },
  { title: 'Unlock', value: 'unlock' },
  { title: 'Eye', value: 'eye' },
  { title: 'Heart', value: 'heart' },
  { title: 'Lightbulb', value: 'lightbulb' },
  { title: 'Target', value: 'target' },
  { title: 'Trophy', value: 'trophy' },
  { title: 'Coins', value: 'coins' },
  { title: 'Wallet', value: 'wallet' },
  { title: 'Credit Card', value: 'credit-card' },
  { title: 'Banknote', value: 'banknote' },
  { title: 'TrendingUp', value: 'trending-up' },
  { title: 'Sparkles', value: 'sparkles' },
  { title: 'Bot', value: 'bot' },
  { title: 'Headphones', value: 'headphones' },
  { title: 'Help Circle', value: 'help-circle' },
];
